### ISSUE TITLE
Bedrading

### ISSUE THREAD

**Issue by SimplyPancake** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time#1]
Bedenk hoe je zo efficient mogelijk de stoplichten aan kan sluiten op de Arduino. 

Alle stoplichten hebben(of kunnen hebben) dezelfde GND. (PinIn)
Edit: het is belangrijk dat we eerst met 1 stoplicht begint en dat die goed werkt. Daarna gaan we steeds meer stoplichten toevoegen

**Comment by ExoPugg** [comment]
test

**Comment by Vylsa** [comment]
Ik heb de bedrading gedaan, alle lampjes hebben hun ground verbonden aan de zijde van de breadboard, en die zijde is dan weer verbonden aan een ground op de arduino. 
![20190111_120236](https://user-images.githubusercontent.com/43268520/51030185-ea340200-1598-11e9-9619-201e27b4bcf6.jpg)
