### ISSUE TITLE
Visuele representatie maken van stoplicht

### ISSUE THREAD

**Issue by ExoPugg** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time#13]
Iemand moet een visuele representatie maken van het stoplicht.

**Comment by SimplyPancake** [comment]
[URL naar plaatje van de layout](https://user-images.githubusercontent.com/43268520/51743106-01e0af80-209c-11e9-8f5f-b6b2ef8ab147.jpg)
