### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ExoPugg** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time#7]
We moeten ook een layout maken van alle pins in fritzing. Zodat het duidelijk is hoe de pins, weerstanden en de lampjes op de arduino zitten.

**Comment by Vylsa** [comment]
Ik heb de layout gemaakt. Hier heb je hem. 
![screenshot 2019-01-11 at 12 32 43](https://user-images.githubusercontent.com/43268520/51039679-ff6b5980-15b5-11e9-9c2c-4327c934b70a.png)
