### ISSUE TITLE
Housing voor de lampjes, het model

### ISSUE THREAD

**Issue by Vylsa** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time#8]
We moeten ook een model maken waarin we kunnen laten zien dat het stoplicht daadwerkelijk werkt.

**Comment by SimplyPancake** [comment]
[Dit is de link naar het plaatje dat we gebruiken voor de bedrading](https://user-images.githubusercontent.com/43268520/51039679-ff6b5980-15b5-11e9-9c2c-4327c934b70a.png)
