### ISSUE TITLE
Array sorteer-taak

### ISSUE THREAD

**Issue by SimplyPancake** [Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time#9]
Schrijf in de code een funcite om een array te sorteren.

De input is:
[6,7,2,3,1,5,4,8]
En de output is:
[1,2,3,4,5,6,7,8]

Ik zou graag willen als Robert het doet!

**Comment by ExoPugg** [comment]
[SortArray.ino.zip](https://github.com/Alberdingk-Thijm-College/4-vwo-arduino-2018-2019-muffin-time/files/2772480/SortArray.ino.zip)
